messages:
  help: "&eAvailable commands&7:"
  add_success: "&7Player &e%player% &7has been added to the &ebanwave&7."
  remove_success: "&7Player &e%player% &7has been removed from the &ebanwave&7."
  start: "&eBanwave is starting&7..."
  end: "&eBanwave has ended."
  unknown_command: "&7Unknown command. Use &e/banwave&7 for help."
  ban_detected: "&7Banwave banned &e%player%&7 &e#%count%&7."
  banwave_completed: "&eBanwave completed&7. &e%removed% &7players have been banned."
  add_command: "&e/banwave add <player> &7- Add player to banwave"
  remove_command: "&e/banwave remove <player> &7- Remove player from banwave"
  start_command: "&e/banwave start &7- Start the banwave"
  end_command: "&e/banwave end &7- End the banwave"
  no_players: "&eNo players are currently banned."
ban_command: "ban %player% Cheating"